import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, mkdir, open, rm, stat, utimes, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { ArtifactStore } from "../src/artifact.js";
import { createCommandRuntime } from "../src/runtime.js";

async function runtime(policy: "never" | "on-truncation" | "always", directory?: string, extra: Record<string, unknown> = {}) { const root = process.cwd(); return createCommandRuntime({ roots: [root], artifactDirectory: directory, maxOutputBytes: 3, manifest: { version: 1, programs: { node: { candidates: [process.execPath], required: true, policy: { artifactPolicy: policy } } } }, ...extra }); }
test("inline output retains byte-correct head and tail with UTF-8 diagnostics", async () => { const r = await runtime("never"); try { const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write(Buffer.from([0x61,0xe2,0x82,0xac,0x62,0xff]))"], cwd: "." }); assert.equal(result.stdout.totalBytes, 6); assert.equal(result.stdout.omittedBytes, 3); assert.equal(result.stdout.lossyUtf8, true); assert.match(result.stdout.text, /3 bytes omitted/); } finally { await r.close(); } });
test("truncated UTF-8 detects independently lossy displayed head and tail", async () => { const r = await runtime("never", undefined, { inlineHeadBytes: 1 }); try { const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write(Buffer.from([0xe2,0x41,0x41,0x82,0xac]))"], cwd: "." }); assert.equal(result.stdout.truncated, true); assert.equal(result.stdout.lossyUtf8, true); } finally { await r.close(); } });
test("on-truncation publishes complete streams and pages them", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const r = await runtime("on-truncation", directory); try { const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write('abcdef');process.stderr.write('XYZ')"], cwd: "." }); assert.equal(result.artifact.status, "published"); const id = result.artifact.id!; assert.deepEqual(await r.readOutput(id, "stdout", 0, 2, "utf8"), { bytes: 2, nextOffset: 2, eof: false, encoding: "utf8", text: "ab", lossyUtf8: false }); const page = await r.readOutput(id, "stdout", 2, 10, "base64"); assert.equal(Buffer.from(page.base64!, "base64").toString(), "cdef"); assert.equal(page.eof, true); await assert.rejects(r.readOutput("../bad", "stdout", 0, 1, "utf8"), /ARTIFACT_NOT_FOUND/); await assert.rejects(r.readOutput(id, "stdout", 99, 1, "utf8"), /INVALID_OUTPUT_OFFSET/); } finally { await r.close(); await rm(directory, { recursive: true, force: true }); } });
test("never is not requested, conditional discards, and always publishes", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const never = await runtime("never", directory); try { assert.equal((await never.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." })).artifact.status, "not-requested"); } finally { await never.close(); } const conditional = await runtime("on-truncation", directory); try { assert.equal((await conditional.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." })).artifact.status, "discarded"); } finally { await conditional.close(); } const always = await runtime("always", directory); try { const result = await always.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); assert.equal(result.artifact.status, "published"); await always.close(); await assert.rejects(always.readOutput(result.artifact.id!, "stdout", 0, 1, "utf8"), /RUNTIME_CLOSING/); } finally { await always.close(); await rm(directory, { recursive: true, force: true }); } });
test("unavailable artifact storage never changes process outcome", async () => { const r = await runtime("always", join(process.cwd(), "package.json", "bad")); try { const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); assert.equal(result.exitCode, 0); assert.equal(result.artifact.status, "unavailable"); } finally { await r.close(); } });
test("quota and stream caps remove unpublishable artifacts", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const quota = await runtime("always", directory, { artifactQuotaBytes: 1 }); try { const result = await quota.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); assert.deepEqual(result.artifact, { status: "unavailable" }); } finally { await quota.close(); } const capped = await runtime("always", directory, { artifactMaxStreamBytes: 1 }); try { const result = await capped.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); assert.deepEqual(result.artifact, { status: "unavailable" }); } finally { await capped.close(); await rm(directory, { recursive: true, force: true }); } });
test("malformed published metadata is not found", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const r = await runtime("always", directory); try { const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); const id = result.artifact.id!; await writeFile(join(directory, id, "meta.json"), JSON.stringify({ version: 1, state: "published", stdoutBytes: 2, stderrBytes: 0 }), "utf8"); await assert.rejects(r.readOutput(id, "stdout", 0, 1, "utf8"), /ARTIFACT_NOT_FOUND/); } finally { await r.close(); await rm(directory, { recursive: true, force: true }); } });
test("exact retained output is not truncated and output pages use bounded reads", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const r = await runtime("on-truncation", directory, { inlineHeadBytes: 1 }); try { const exact = await r.execute({ program: "node", args: ["-e", "process.stdout.write('abc')"], cwd: "." }); assert.equal(exact.stdout.truncated, false); assert.equal(exact.stdout.omittedBytes, 0); assert.equal(exact.stdout.text, "abc"); assert.doesNotMatch(exact.stdout.text, /omitted/); const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write('abcdef')"], cwd: "." }); const id = result.artifact.id!; const handle = await open(join(directory, id, "stdout"), "r+"); try { await handle.truncate(4); } finally { await handle.close(); } await assert.rejects(r.readOutput(id, "stdout", 2, 1, "utf8"), /ARTIFACT_NOT_FOUND/); } finally { await r.close(); await rm(directory, { recursive: true, force: true }); } });
test("recovery preserves live foreign spools and removes expired spools", async () => { const fs = await import("node:fs/promises"); const directory = await mkdtemp(join(tmpdir(), "artifact-")); const a = new ArtifactStore(directory, 1_000, 1_000); try { await a.start(); const live = await a.spool(); await live.append("stdout", Buffer.from("ok")); const b = new ArtifactStore(directory, 1_000, 1_000); await b.start(); await fs.stat(live.path); const id = await a.publish(live); assert.equal((await b.read(id, "stdout", 0, 2, "utf8")).text, "ok"); const stale = await a.spool(); const owner = JSON.parse(await fs.readFile(join(stale.path, "owner.json"), "utf8")); await fs.writeFile(join(stale.path, "owner.json"), JSON.stringify({ ...owner, leaseUntil: Date.now() - 1 })); const c = new ArtifactStore(directory, 1_000, 1_000); await c.start(); await assert.rejects(fs.stat(stale.path)); await Promise.all([b.close(), c.close()]); } finally { await a.close(); await rm(directory, { recursive: true, force: true }); } });
test("recovery preserves a spool with partial owner metadata", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const a = new ArtifactStore(directory, 1_000, 1_000); try { await a.start(); const spool = await a.spool(); await writeFile(join(spool.path, "owner.json"), "{\"runtimeId\":"); const b = new ArtifactStore(directory, 1_000, 1_000); await b.start(); await stat(spool.path); await b.close(); } finally { await a.close(); await rm(directory, { recursive: true, force: true }); } });
test("startup recovery preserves fresh ownerless locks and staging but removes old ones", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); try { const lock = join(directory, ".lock"); const fresh = join(directory, ".spool-fresh.new"); const old = join(directory, ".spool-old.new"); await Promise.all([mkdir(lock), mkdir(fresh), mkdir(old)]); await utimes(lock, new Date(), new Date()); await utimes(old, new Date(Date.now() - 61_000), new Date(Date.now() - 61_000)); const a = new ArtifactStore(directory, 1_000, 1_000); await a.start(); await stat(lock); await stat(fresh); await a.close(); await rm(lock, { recursive: true }); const b = new ArtifactStore(directory, 1_000, 1_000); await b.start(); await stat(fresh); await assert.rejects(stat(old)); await b.close(); await mkdir(lock); await utimes(lock, new Date(Date.now() - 61_000), new Date(Date.now() - 61_000)); const c = new ArtifactStore(directory, 1_000, 1_000); await c.start(); const spool = await c.spool(); await spool.append("stdout", Buffer.from("ok")); assert.match(await c.publish(spool), /^[a-f0-9]{32}$/); await c.close(); } finally { await rm(directory, { recursive: true, force: true }); } });
test("read rejects expired published artifacts immediately", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const store = new ArtifactStore(directory, 1, 1_000); try { await store.start(); const spool = await store.spool(); await spool.append("stdout", Buffer.from("ok")); const id = await store.publish(spool); const meta = join(directory, id, "meta.json"); const value = JSON.parse(await (await import("node:fs/promises")).readFile(meta, "utf8")); await writeFile(meta, JSON.stringify({ ...value, publishedAt: Date.now() - 2 })); await assert.rejects(store.read(id, "stdout", 0, 1, "utf8"), /ARTIFACT_NOT_FOUND/); } finally { await store.close(); await rm(directory, { recursive: true, force: true }); } });
test("startup failure disables persistence without blocking execution", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); try { await writeFile(join(directory, "marker"), "x"); const broken = new ArtifactStore(join(directory, "marker", "bad"), 1_000, 1_000); await broken.start(); await assert.rejects(broken.spool(), /ARTIFACT_UNAVAILABLE/); } finally { await rm(directory, { recursive: true, force: true }); } });
test("close clears its deadline timer when cleanup is immediate", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); try { const child = spawn(process.execPath, ["--input-type=module", "-e", `import { ArtifactStore } from ${JSON.stringify(new URL("../src/artifact.js", import.meta.url).href)}; const store = new ArtifactStore(${JSON.stringify(directory)}, 1_000, 1_000); await store.start(); await store.spool(); await store.close(2_000);`], { stdio: "ignore" }); const exited = await Promise.race([new Promise<true>(resolve => child.once("exit", () => resolve(true))), new Promise<false>(resolve => setTimeout(() => resolve(false), 1_000))]); if (!exited) child.kill(); assert.equal(exited, true); } finally { await rm(directory, { recursive: true, force: true }); } });
