import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, open, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { ArtifactStore } from "../src/artifact.js";
import { createCommandRuntime } from "../src/runtime.js";

async function runtime(policy: "never" | "on-truncation" | "always", directory?: string, extra: Record<string, unknown> = {}) { const root = process.cwd(); return createCommandRuntime({ roots: [root], artifactDirectory: directory, maxOutputBytes: 3, manifest: { version: 1, programs: { node: { candidates: [process.execPath], required: true, policy: { artifactPolicy: policy } } } }, ...extra }); }
test("inline output retains byte-correct head and tail with UTF-8 diagnostics", async () => { const r = await runtime("never"); try { const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write(Buffer.from([0x61,0xe2,0x82,0xac,0x62,0xff]))"], cwd: "." }); assert.equal(result.stdout.totalBytes, 6); assert.equal(result.stdout.omittedBytes, 3); assert.equal(result.stdout.lossyUtf8, true); assert.match(result.stdout.text, /3 bytes omitted/); } finally { await r.close(); } });
test("on-truncation publishes complete streams and pages them", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const r = await runtime("on-truncation", directory); try { const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write('abcdef');process.stderr.write('XYZ')"], cwd: "." }); assert.equal(result.artifact.status, "published"); const id = result.artifact.id!; assert.deepEqual(await r.readOutput(id, "stdout", 0, 2, "utf8"), { bytes: 2, nextOffset: 2, eof: false, encoding: "utf8", text: "ab", lossyUtf8: false }); const page = await r.readOutput(id, "stdout", 2, 10, "base64"); assert.equal(Buffer.from(page.base64!, "base64").toString(), "cdef"); assert.equal(page.eof, true); await assert.rejects(r.readOutput("../bad", "stdout", 0, 1, "utf8"), /ARTIFACT_NOT_FOUND/); await assert.rejects(r.readOutput(id, "stdout", 99, 1, "utf8"), /INVALID_OUTPUT_OFFSET/); } finally { await r.close(); await rm(directory, { recursive: true, force: true }); } });
test("never is not requested, conditional discards, and always publishes", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const never = await runtime("never", directory); try { assert.equal((await never.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." })).artifact.status, "not-requested"); } finally { await never.close(); } const conditional = await runtime("on-truncation", directory); try { assert.equal((await conditional.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." })).artifact.status, "discarded"); } finally { await conditional.close(); } const always = await runtime("always", directory); try { const result = await always.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); assert.equal(result.artifact.status, "published"); await always.close(); await assert.rejects(always.readOutput(result.artifact.id!, "stdout", 0, 1, "utf8"), /RUNTIME_CLOSING/); } finally { await always.close(); await rm(directory, { recursive: true, force: true }); } });
test("unavailable artifact storage never changes process outcome", async () => { const r = await runtime("always", join(process.cwd(), "package.json", "bad")); try { const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); assert.equal(result.exitCode, 0); assert.equal(result.artifact.status, "unavailable"); } finally { await r.close(); } });
test("quota and stream caps remove unpublishable artifacts", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const quota = await runtime("always", directory, { artifactQuotaBytes: 1 }); try { const result = await quota.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); assert.deepEqual(result.artifact, { status: "unavailable" }); } finally { await quota.close(); } const capped = await runtime("always", directory, { artifactMaxStreamBytes: 1 }); try { const result = await capped.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); assert.deepEqual(result.artifact, { status: "unavailable" }); } finally { await capped.close(); await rm(directory, { recursive: true, force: true }); } });
test("malformed published metadata is not found", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const r = await runtime("always", directory); try { const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write('ok')"], cwd: "." }); const id = result.artifact.id!; await writeFile(join(directory, id, "meta.json"), JSON.stringify({ version: 1, state: "published", stdoutBytes: 2, stderrBytes: 0 }), "utf8"); await assert.rejects(r.readOutput(id, "stdout", 0, 1, "utf8"), /ARTIFACT_NOT_FOUND/); } finally { await r.close(); await rm(directory, { recursive: true, force: true }); } });
test("exact retained output is not truncated and output pages use bounded reads", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); const r = await runtime("on-truncation", directory, { inlineHeadBytes: 1 }); try { const exact = await r.execute({ program: "node", args: ["-e", "process.stdout.write('abc')"], cwd: "." }); assert.equal(exact.stdout.truncated, false); assert.equal(exact.stdout.text, "abc"); const result = await r.execute({ program: "node", args: ["-e", "process.stdout.write('abcdef')"], cwd: "." }); const id = result.artifact.id!; const handle = await open(join(directory, id, "stdout"), "r+"); try { await handle.truncate(4); } finally { await handle.close(); } await assert.rejects(r.readOutput(id, "stdout", 2, 1, "utf8"), /ARTIFACT_NOT_FOUND/); } finally { await r.close(); await rm(directory, { recursive: true, force: true }); } });
test("startup removes ownerless stale spools and disables unavailable storage", async () => { const directory = await mkdtemp(join(tmpdir(), "artifact-")); try { const stale = join(directory, ".spool-orphan"); await writeFile(join(directory, "marker"), "x"); await (await import("node:fs/promises")).mkdir(stale); const store = new ArtifactStore(directory, 1_000, 1_000); await store.start(); await assert.rejects((await import("node:fs/promises")).stat(stale)); await store.close(); const broken = new ArtifactStore(join(directory, "marker", "bad"), 1_000, 1_000); await broken.start(); await assert.rejects(broken.spool(), /ARTIFACT_UNAVAILABLE/); } finally { await rm(directory, { recursive: true, force: true }); } });
